services:
  tex:
    image: latex-docker:latest
    build: .
    working_dir: /work
    volumes:
      - ./:/work
    environment:
      TEX_MAIN: "*.tex"
      TEX_ENGINE: "auto"
      TEX_WATCH: "0"
    command: ["bash", "-lc", "texbuild"]
